version: '3.3'
services:
  # Development environment
  dev:
    container_name: website
    build:
      context: ../../.
      dockerfile: docker/Development/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  # Run tests without watching
  tests:
    build:
      context: ../../.
      dockerfile: docker/Development/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CI=true
    command: ["npm", "test"]
