version: '3.3'
services:
  web:
    container_name: website
    build:
      context: ../../.
      dockerfile: docker/Development/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  tests:
    build:
      context: ../../.
      dockerfile: docker/Development/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: ["npm", "run", "test"]