version: '3.3'
# Create production build and host on port 80
services:
  production:
    container_name: website
    build:
      context: ../../.
      dockerfile: docker/Production/Dockerfile
    ports:
      - '80:80'